---
ID: "4b7bb5d9-3a4a-4a63-9219-4495182fde4d"
Parent: "55c817c9-6226-460b-b015-282776c95ed0"
Template: "55c817c9-6226-460b-b015-282776c95ed0"
Path: /sitecore/templates/Project/Common/Content Types/Hackathon/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T190811Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
