---
ID: "f6fb8be1-ae8a-4cea-bca8-da5d08abbdab"
Parent: "da9d461e-8813-40b2-9912-446be168602a"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/TeamHorizon/Hackathon/Presentation/Rendering Variants/Link/Default
DB: master
BranchID: "4d660f84-930a-437f-9457-e9c4cd8f674c"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{D9F3C5DF-05F7-48EE-AD81-53956BDFA605}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T101547Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
