---
ID: "d4e1d02c-e67f-449d-bf0a-255caa775600"
Parent: "4fa29070-7d23-480d-b0a8-c5d4842f4d0d"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/TeamHorizon/Hackathon/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T101500Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
