---
ID: "ace5bb49-6dc3-4610-b4b2-a89bffc2faf6"
Parent: "8e72f784-d82c-4f07-8e9a-9b67f690ab72"
Template: "8e72f784-d82c-4f07-8e9a-9b67f690ab72"
Path: /sitecore/templates/Project/TeamHorizon/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T101155Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
